export interface Course {
    id: string;
    code: string; // Product code like SC-200, AZ-400
    title: string;
    description: string;
    price: number; // Price in USD (exact Skillable public prices)
    image: string;
    category: string; // For colored overlay
    tags: string[];
    level: 'Beginner' | 'Intermediate' | 'Advanced';
    requiresAzurePortal?: boolean; // NEW: Flag for Azure Portal access
}

// All courses from Skillable with exact public prices
export const MOCK_COURSES: Course[] = [
    {
        id: 'm55631a',
        code: 'M55631A',
        title: 'Mastering Windows 11 Deployment with MDT',
        description: 'Learn to deploy Windows 11 using Microsoft Deployment Toolkit',
        price: 45.15,
        image: '/images/course.png',
        category: 'Microsoft Training',
        tags: ['Windows', 'Deployment'],
        level: 'Intermediate',
    },
    {
        id: 'ab-6002',
        code: 'AB-6002',
        title: 'Introduction to finance in Dynamics 365',
        description: 'Get started with finance in Dynamics 365',
        price: 15.0, // 25.0 - 10
        image: '/images/course.png',
        category: 'Microsoft Dynamics 365',
        tags: ['Dynamics', 'Finance'],
        level: 'Beginner',
    },
    {
        id: 'dp-3029',
        code: 'DP-3029',
        title: 'Work smarter with Copilot in Microsoft Fabric [Cloud Slice Provided]',
        description: 'Learn to use Copilot in Microsoft Fabric',
        price: 45.0,
        image: '/images/course.png',
        category: 'Microsoft Data Platform',
        tags: ['Fabric', 'Copilot', 'AI'],
        level: 'Intermediate',
    },
    {
        id: 'dp-3028',
        code: 'DP-3028',
        title: 'Implement Generative AI Engineering with Azure Databricks [Cloud Slice Provided]',
        description: 'Build generative AI solutions with Azure Databricks',
        price: 46.0,
        image: '/images/course.png',
        category: 'Microsoft Data Platform',
        tags: ['AI', 'Databricks', 'Azure'],
        level: 'Advanced',
    },
    {
        id: 'm55601-1a',
        code: 'M55601-1A',
        title: 'Implementing and Managing Microsoft Virtualization Platforms',
        description: 'Learn virtualization with Microsoft technologies',
        price: 45.65, // 55.65 - 10
        image: '/images/course.png',
        category: 'Microsoft Training',
        tags: ['Virtualization', 'Hyper-V'],
        level: 'Advanced',
    },
    {
        id: 'ws011wv-2025',
        code: 'WS011WV-2025',
        title: 'Windows Server 2025 Administration',
        description: 'Administer Windows Server 2025',
        price: 68.25,
        image: '/images/course.png',
        category: 'Microsoft Training',
        tags: ['Windows Server', 'Administration'],
        level: 'Intermediate',
    },
    {
        id: 'dp-700t00-a',
        code: 'DP-700T00-A',
        title: 'Implement data engineering solutions using Microsoft Fabric [Cloud Slice Provided]',
        description: 'Build data engineering solutions with Microsoft Fabric',
        price: 179.99,
        image: '/images/course.png',
        category: 'Microsoft Data Platform',
        tags: ['Fabric', 'Data Engineering'],
        level: 'Advanced',
    },
    {
        id: 'az-2007',
        code: 'AZ-2007',
        title: 'Accelerate app development by using GitHub Copilot',
        description: 'Use GitHub Copilot to accelerate development',
        price: 15.0, // 25.0 - 10
        image: '/images/course.png',
        category: 'Microsoft Azure',
        tags: ['GitHub', 'Copilot', 'Development'],
        level: 'Beginner',
    },
    {
        id: 'ai-3026',
        code: 'AI-3026',
        title: 'Develop AI agents on Azure [Cloud Slice Provided]',
        description: 'Build intelligent AI agents on Azure',
        price: 40.0,
        image: '/images/course.png',
        category: 'Microsoft AI',
        tags: ['AI', 'Azure', 'Agents'],
        level: 'Advanced',
    },
    {
        id: 'sc-401t00-a',
        code: 'SC-401T00-A',
        title: 'Microsoft Information Security Administrator',
        description: 'Administer information security in Microsoft 365',
        price: 41.0,
        image: '/images/course.png',
        category: 'Microsoft Security',
        tags: ['Security', 'Microsoft 365'],
        level: 'Advanced',
    },
    {
        id: 'ms-4023',
        code: 'MS-4023',
        title: 'Explore Microsoft 365 Copilot Chat',
        description: 'Learn to use Microsoft 365 Copilot Chat',
        price: 20.0,
        image: '/images/course.png',
        category: 'Microsoft 365',
        tags: ['Copilot', 'Microsoft 365'],
        level: 'Beginner',
    },
    {
        id: 'ms-4010',
        code: 'MS-4010',
        title: 'Extend Microsoft 365 Copilot with declarative agents by using Visual Studio Code',
        description: 'Build declarative agents for Microsoft 365 Copilot',
        price: 20.0,
        image: '/images/course.png',
        category: 'Microsoft 365',
        tags: ['Copilot', 'Development', 'VS Code'],
        level: 'Intermediate',
    },
    {
        id: 'm55624a',
        code: 'M55624A',
        title: 'Windows 11 Advanced Administration',
        description: 'Advanced administration techniques for Windows 11',
        price: 45.65, // 55.65 - 10
        image: '/images/course.png',
        category: 'Microsoft Training',
        tags: ['Windows 11', 'Administration'],
        level: 'Advanced',
    },
    {
        id: 'az-2001',
        code: 'AZ-2001-',
        title: 'A Implement security through a pipeline using Azure DevOps [Cloud Slice Provided]',
        description: 'Implement security in Azure DevOps pipelines',
        price: 21.0,
        image: '/images/course.png',
        category: 'Microsoft Azure',
        tags: ['Azure', 'DevOps', 'Security'],
        level: 'Intermediate',
    },
    {
        id: 'm55625a',
        code: 'M55625A',
        title: 'Whats new in Microsoft Server 2025',
        description: 'Explore new features in Windows Server 2025',
        price: 15.0,
        image: '/images/course.png',
        category: 'Microsoft Training',
        tags: ['Windows Server', 'New Features'],
        level: 'Beginner',
    },
    {
        id: 'm55604a',
        code: 'M55604A',
        title: 'Using AI and Copilot in the Microsoft Power Platform',
        description: 'Leverage AI and Copilot in Power Platform',
        price: 35.7,
        image: '/images/course.png',
        category: 'Microsoft Training',
        tags: ['Power Platform', 'AI', 'Copilot'],
        level: 'Intermediate',
    },
    {
        id: 'sc-200t00-a',
        code: 'SC-200T00-A',
        title: 'Microsoft Security Operations Analyst [Cloud Slice Provided]',
        description: 'Mitigate threats using Microsoft 365 Defender, Microsoft Defender for Cloud, and Microsoft Sentinel',
        price: 57.74,
        image: '/images/course.png',
        category: 'Microsoft Security',
        tags: ['Security', 'Microsoft 365', 'Sentinel'],
        level: 'Advanced',
        requiresAzurePortal: true,
    },
    {
        id: 'dp-3020',
        code: 'DP-3020',
        title: 'Develop data-driven applications with Azure SQL Database [Cloud Slice Provided]',
        description: 'Build applications with Azure SQL Database',
        price: 50.4,
        image: '/images/course.png',
        category: 'Microsoft Data Platform',
        tags: ['Azure SQL', 'Database', 'Development'],
        level: 'Intermediate',
    },
    {
        id: 'sc-5004',
        code: 'SC-5004',
        title: 'Defend against cyberthreats with Microsoft Defender XDR',
        description: 'Learn to defend against threats with Defender XDR',
        price: 21.0,
        image: '/images/course.png',
        category: 'Microsoft Security',
        tags: ['Security', 'Defender', 'XDR'],
        level: 'Intermediate',
    },
    {
        id: 'mb-7005',
        code: 'MB-7005',
        title: 'Create and manage journeys with Dynamics 365 Customer Insights',
        description: 'Manage customer journeys in Dynamics 365',
        price: 21.0,
        image: '/images/course.png',
        category: 'Microsoft Dynamics 365',
        tags: ['Dynamics', 'Customer Insights'],
        level: 'Intermediate',
    },
    {
        id: 'mb-7006',
        code: 'MB-7006',
        title: 'Create and manage segments in Dynamics 365 Customer Insights – Data',
        description: 'Segment customers in Dynamics 365 Customer Insights',
        price: 21.0,
        image: '/images/course.png',
        category: 'Microsoft Dynamics 365',
        tags: ['Dynamics', 'Customer Insights', 'Segmentation'],
        level: 'Intermediate',
    },
    {
        id: 'mb-280t01',
        code: 'MB-280T01',
        title: 'MB280T03 Dynamics 365 Customer Experience Analyst',
        description: 'Become a Dynamics 365 Customer Experience Analyst',
        price: 63.0,
        image: '/images/course.png',
        category: 'Microsoft Dynamics 365',
        tags: ['Dynamics', 'Customer Experience'],
        level: 'Advanced',
    },
    {
        id: 'ai-3025',
        code: 'AI-3025',
        title: 'Work Smarter with AI',
        description: 'Learn to work more efficiently with AI',
        price: 10.5,
        image: '/images/course.png',
        category: 'Microsoft AI',
        tags: ['AI', 'Productivity'],
        level: 'Beginner',
    },
    {
        id: 'az-400t00-a',
        code: 'AZ-400T00-A',
        title: 'Designing and Implementing Microsoft DevOps Solutions [Cloud Slice Provided]',
        description: 'Design and implement strategies for collaboration, code, infrastructure, source control, security, compliance, continuous integration, testing, delivery, monitoring, and feedback',
        price: 100.0,
        image: '/images/course.png',
        category: 'Microsoft Azure',
        tags: ['Azure', 'DevOps', 'CI/CD'],
        level: 'Advanced',
        requiresAzurePortal: true,
    },
    {
        id: 'az-2008',
        code: 'AZ-2008',
        title: 'DevOps Foundations: The Core Principles and Practices [Cloud Slice Provided]',
        description: 'Learn DevOps foundations and best practices',
        price: 31.5,
        image: '/images/course.png',
        category: 'Microsoft Azure',
        tags: ['DevOps', 'Foundations'],
        level: 'Beginner',
    },
    {
        id: 'ms-4002',
        code: 'MS-4002',
        title: 'Prepare security and compliance to support Microsoft 365 Copilot',
        description: 'Prepare your environment for Microsoft 365 Copilot',
        price: 21.0,
        image: '/images/course.png',
        category: 'Microsoft 365',
        tags: ['Security', 'Compliance', 'Copilot'],
        level: 'Intermediate',
    },
    {
        id: 'sc-300t00-a',
        code: 'SC-300T00-A',
        title: 'Microsoft Identity and Access Administrator [Cloud Slice Provided]',
        description: 'Implement and manage identity and access solutions',
        price: 41.99,
        image: '/images/course.png',
        category: 'Microsoft Security',
        tags: ['Identity', 'Access', 'Security'],
        level: 'Advanced',
        requiresAzurePortal: true,
    },
    {
        id: 'ai-3022',
        code: 'AI-3022',
        title: 'Implement AI Skills in Azure AI Search [Cloud Slice Provided]',
        description: 'Build AI-powered search solutions',
        price: 32.55,
        image: '/images/course.png',
        category: 'Microsoft AI',
        tags: ['AI', 'Search', 'Azure'],
        level: 'Intermediate',
    },
    {
        id: 'az-2006',
        code: 'AZ-2006',
        title: 'Automate Azure Load Testing by using GitHub Actions [Cloud Slice Provided]',
        description: 'Automate load testing with GitHub Actions',
        price: 63.0,
        image: '/images/course.png',
        category: 'Microsoft Azure',
        tags: ['Azure', 'Testing', 'GitHub Actions'],
        level: 'Intermediate',
    },
    {
        id: 'mb-280t04',
        code: 'MB-280T04',
        title: 'Configure a Dynamics 365 customer experience solution',
        description: 'Configure Dynamics 365 for customer experience',
        price: 25.2,
        image: '/images/course.png',
        category: 'Microsoft Dynamics 365',
        tags: ['Dynamics', 'Configuration'],
        level: 'Intermediate',
    },
    {
        id: 'mb-280t03',
        code: 'MB-280T03',
        title: 'Design and deliver powerful customer experiences with Dynamics 365 Customer Insights',
        description: 'Create customer experiences with Dynamics 365',
        price: 25.2,
        image: '/images/course.png',
        category: 'Microsoft Dynamics 365',
        tags: ['Dynamics', 'Customer Insights'],
        level: 'Intermediate',
    },
    {
        id: 'mb-280t02',
        code: 'MB-280T02',
        title: 'Empower sellers with Dynamics 365 Sales and Microsoft 365 Copilot for Sales',
        description: 'Use Dynamics 365 Sales with Copilot',
        price: 25.2,
        image: '/images/course.png',
        category: 'Microsoft Dynamics 365',
        tags: ['Dynamics', 'Sales', 'Copilot'],
        level: 'Intermediate',
    },
    {
        id: 'mb-280t01-config',
        code: 'MB-280T01',
        title: 'Configure Dynamics 365 customer experience model-driven apps',
        description: 'Configure model-driven apps in Dynamics 365',
        price: 25.2,
        image: '/images/course.png',
        category: 'Microsoft Dynamics 365',
        tags: ['Dynamics', 'Model-driven Apps'],
        level: 'Intermediate',
    },
    {
        id: 'sc-100t00-a',
        code: 'SC-100T00-A',
        title: 'Microsoft Cybersecurity Architect [Cloud Slice Provided]',
        description: 'Design and evaluate cybersecurity strategies',
        price: 28.35,
        image: '/images/course.png',
        category: 'Microsoft Security',
        tags: ['Security', 'Architecture'],
        level: 'Advanced',
    },
    {
        id: 'az-140t00-a',
        code: 'AZ-140T00-A',
        title: 'Configuring and Operating Microsoft Azure Virtual Desktop [Cloud Slice Provided]',
        description: 'Configure and manage Azure Virtual Desktop',
        price: 73.49,
        image: '/images/course.png',
        category: 'Microsoft Azure',
        tags: ['Azure', 'Virtual Desktop'],
        level: 'Intermediate',
    },
    {
        id: 'dp-3021',
        code: 'DP-3021',
        title: 'Migrate to and configure Azure Database for PostgreSQL [Cloud Slice Provided]',
        description: 'Migrate and configure PostgreSQL on Azure',
        price: 41.99,
        image: '/images/course.png',
        category: 'Microsoft Data Platform',
        tags: ['Azure', 'PostgreSQL', 'Migration'],
        level: 'Intermediate',
    },
    {
        id: 'az-1010',
        code: 'AZ-1010',
        title: 'Deploy and manage Azure Arc-enabled Servers [Cloud Slice Provided]',
        description: 'Manage servers with Azure Arc',
        price: 31.49,
        image: '/images/course.png',
        category: 'Microsoft Azure',
        tags: ['Azure', 'Arc', 'Servers'],
        level: 'Intermediate',
    },
    {
        id: 'ai-3019',
        code: 'AI-3019',
        title: 'Develop AI-powered solutions with Azure Database for PostgreSQL [Cloud Slice Provided]',
        description: 'Build AI solutions with PostgreSQL',
        price: 36.75,
        image: '/images/course.png',
        category: 'Microsoft AI',
        tags: ['AI', 'PostgreSQL', 'Azure'],
        level: 'Advanced',
    },
    {
        id: 'pl-400t00-a',
        code: 'PL-400T00-A',
        title: 'Microsoft Power Platform Developer [Cloud Slice Provided]',
        description: 'Develop solutions on Power Platform',
        price: 41.99,
        image: '/images/course.png',
        category: 'Microsoft Power Platform',
        tags: ['Power Platform', 'Development'],
        level: 'Advanced',
    },
    {
        id: 'az-1007',
        code: 'AZ-1007',
        title: 'Deploy and administer Linux virtual machines on Azure [Cloud Slice Provided]',
        description: 'Manage Linux VMs on Azure',
        price: 21.0,
        image: '/images/course.png',
        category: 'Microsoft Azure',
        tags: ['Azure', 'Linux', 'VMs'],
        level: 'Intermediate',
    },
    {
        id: 'pl-300t00-a',
        code: 'PL-300T00-A',
        title: 'Design and Manage Analytics Solutions Using Power BI [Cloud Slice Provided]',
        description: 'Prepare the data, model the data, visualize and analyze the data, and deploy and maintain deliverables',
        price: 40.23,
        image: '/images/course.png',
        category: 'Microsoft Power Platform',
        tags: ['Power BI', 'Data', 'Analytics'],
        level: 'Intermediate',
    },
    {
        id: 'az-104t00-a',
        code: 'AZ-104T00-A',
        title: 'Microsoft Azure Administrator [Cloud Slice Provided]',
        description: 'Implement, manage, and monitor an organization\'s Microsoft Azure environment',
        price: 24.24,
        image: '/images/course.png',
        category: 'Microsoft Azure',
        tags: ['Azure', 'Administration'],
        level: 'Intermediate',
        requiresAzurePortal: true,
    },
    {
        id: 'az-500t00-a',
        code: 'AZ-500T00-A',
        title: 'Microsoft Azure Security Technologies [Cloud Slice Provided]',
        description: 'Implement security controls and threat protection',
        price: 22.04,
        image: '/images/course.png',
        category: 'Microsoft Azure',
        tags: ['Azure', 'Security'],
        level: 'Advanced',
        requiresAzurePortal: true,
    },
    {
        id: 'az-204t00-a',
        code: 'AZ-204T00-A',
        title: 'Developing Solutions for Microsoft Azure [Cloud Slice Provided]',
        description: 'Develop Azure compute solutions, storage, security, and more',
        price: 27.55,
        image: '/images/course.png',
        category: 'Microsoft Azure',
        tags: ['Azure', 'Development'],
        level: 'Advanced',
        requiresAzurePortal: true,
    },
    {
        id: 'az-900t00-a',
        code: 'AZ-900T00-A',
        title: 'Introduction to Microsoft Azure [Cloud Slice Provided]',
        description: 'Learn Azure fundamentals and core services',
        price: 11.01,
        image: '/images/course.png',
        category: 'Microsoft Azure',
        tags: ['Azure', 'Fundamentals'],
        level: 'Beginner',
    },
    {
        id: 'ai-900t00-a',
        code: 'AI-900T00-A',
        title: 'Microsoft Azure AI Fundamentals [Cloud Slice Provided]',
        description: 'Learn AI fundamentals on Azure',
        price: 16.53,
        image: '/images/course.png',
        category: 'Microsoft AI',
        tags: ['AI', 'Fundamentals', 'Azure'],
        level: 'Beginner',
    },
    {
        id: 'dp-900t00-a',
        code: 'DP-900T00-A',
        title: 'Introduction to Microsoft Azure Data [Cloud Slice Provided]',
        description: 'Learn data fundamentals on Azure',
        price: 34.93,
        image: '/images/course.png',
        category: 'Microsoft Data Platform',
        tags: ['Data', 'Fundamentals', 'Azure'],
        level: 'Beginner',
    },
    {
        id: 'pl-900t00-a',
        code: 'PL-900T00-A',
        title: 'Microsoft Power Platform Fundamentals',
        description: 'Learn Power Platform fundamentals',
        price: 29.1,
        image: '/images/course.png',
        category: 'Microsoft Power Platform',
        tags: ['Power Platform', 'Fundamentals'],
        level: 'Beginner',
    },
    {
        id: 'sc-900t00-a',
        code: 'SC-900T00-A',
        title: 'Introduction to Microsoft Security, Compliance, and Identity [Cloud Slice Provided]',
        description: 'Learn security, compliance, and identity fundamentals',
        price: 19.46,
        image: '/images/course.png',
        category: 'Microsoft Security',
        tags: ['Security', 'Compliance', 'Identity'],
        level: 'Beginner',
    },
    {
        id: 'ms-700t00-a',
        code: 'MS-700T00-A',
        title: 'Managing Microsoft Teams',
        description: 'Configure and manage Microsoft Teams',
        price: 19.83,
        image: '/images/course.png',
        category: 'Microsoft 365',
        tags: ['Teams', 'Collaboration'],
        level: 'Intermediate',
    },
    {
        id: 'ms-102t00-a',
        code: 'MS-102T00-A',
        title: 'Microsoft 365 Administrator Essentials',
        description: 'Administer Microsoft 365 services',
        price: 39.68,
        image: '/images/course.png',
        category: 'Microsoft 365',
        tags: ['Microsoft 365', 'Administration'],
        level: 'Intermediate',
    },
    {
        id: 'md-102t00-a',
        code: 'MD-102T00-A',
        title: 'Microsoft 365 Endpoint Administrator',
        description: 'Deploy and manage endpoints in Microsoft 365',
        price: 75.69,
        image: '/images/course.png',
        category: 'Microsoft 365',
        tags: ['Endpoint', 'Administration'],
        level: 'Advanced',
    },
    {
        id: 'dp-100t01-a',
        code: 'DP-100T01-A',
        title: 'Designing and Implementing a Data Science Solution on Azure [Cloud Slice Provided]',
        description: 'Build data science solutions on Azure',
        price: 108.15,
        image: '/images/course.png',
        category: 'Microsoft Data Platform',
        tags: ['Data Science', 'Azure', 'ML'],
        level: 'Advanced',
        requiresAzurePortal: true,
    },
    {
        id: 'dp-300t00-a',
        code: 'DP-300T00-A',
        title: 'Implement scalable database solutions using Azure SQL [Cloud Slice Provided]',
        description: 'Administer Azure SQL databases',
        price: 29.11,
        image: '/images/course.png',
        category: 'Microsoft Data Platform',
        tags: ['Azure SQL', 'Database'],
        level: 'Advanced',
    },
    {
        id: 'dp-420t00-a',
        code: 'DP-420T00-A',
        title: 'Design and implement cloud-native applications with Microsoft Azure Cosmos DB [Cloud Slice Provided]',
        description: 'Build applications with Cosmos DB',
        price: 86.51,
        image: '/images/course.png',
        category: 'Microsoft Data Platform',
        tags: ['Cosmos DB', 'NoSQL', 'Azure'],
        level: 'Advanced',
    },
    {
        id: 'dp-600t00-a',
        code: 'DP-600T00-A',
        title: 'Implementing Analytics Solutions Using Microsoft Fabric [Cloud Slice Provided]',
        description: 'Implement analytics with Microsoft Fabric',
        price: 139.99,
        image: '/images/course.png',
        category: 'Microsoft Data Platform',
        tags: ['Fabric', 'Analytics'],
        level: 'Advanced',
    },
    {
        id: 'ai-102t00-a',
        code: 'AI-102T00-A',
        title: 'Design and Implement a Microsoft Azure AI Solution [Cloud Slice Provided]',
        description: 'Build AI solutions on Azure',
        price: 38.58,
        image: '/images/course.png',
        category: 'Microsoft AI',
        tags: ['AI', 'Azure'],
        level: 'Advanced',
        requiresAzurePortal: true,
    },
    {
        id: 'pl-200t00-a',
        code: 'PL-200T00-A',
        title: 'Microsoft Power Platform Functional Consultant',
        description: 'Implement Power Platform solutions',
        price: 32.43,
        image: '/images/course.png',
        category: 'Microsoft Power Platform',
        tags: ['Power Platform', 'Consulting'],
        level: 'Intermediate',
    },
    {
        id: 'mb-230t01-a',
        code: 'MB-230T01-A',
        title: 'Microsoft Dynamics 365 Customer Service',
        description: 'Configure and use Dynamics 365 Customer Service',
        price: 23.8,
        image: '/images/course.png',
        category: 'Microsoft Dynamics 365',
        tags: ['Dynamics', 'Customer Service'],
        level: 'Intermediate',
    },
    {
        id: 'mb-240t00-a',
        code: 'MB-240T00-A',
        title: 'Microsoft Dynamics 365 Field Service',
        description: 'Configure and use Dynamics 365 Field Service',
        price: 34.6,
        image: '/images/course.png',
        category: 'Microsoft Dynamics 365',
        tags: ['Dynamics', 'Field Service'],
        level: 'Intermediate',
    },
    {
        id: 'mb-500t00-a',
        code: 'MB-500T00-A',
        title: 'Microsoft Dynamics 365 Finance and Operations Apps Developer',
        description: 'Develop for Dynamics 365 Finance and Operations',
        price: 77.86,
        image: '/images/course.png',
        category: 'Microsoft Dynamics 365',
        tags: ['Dynamics', 'Development', 'Finance'],
        level: 'Advanced',
    },
    {
        id: 'mb-800t00-a',
        code: 'MB-800T00-A',
        title: 'Microsoft Dynamics 365 Business Central Functional Consultant',
        description: 'Implement Business Central solutions',
        price: 42.82,
        image: '/images/course.png',
        category: 'Microsoft Dynamics 365',
        tags: ['Dynamics', 'Business Central'],
        level: 'Intermediate',
    },
    {
        id: 'az-700t00-a',
        code: 'AZ-700T00-A',
        title: 'Design and Implement Microsoft Azure Networking Solutions [Cloud Slice Provided]',
        description: 'Design and implement Azure networking',
        price: 71.65,
        image: '/images/course.png',
        category: 'Microsoft Azure',
        tags: ['Azure', 'Networking'],
        level: 'Advanced',
    },
    {
        id: 'az-800t00-a',
        code: 'AZ-800T00-A',
        title: 'Administering Windows Server Hybrid Core Infrastructure [Cloud Slice Provided]',
        description: 'Administer hybrid Windows Server infrastructure',
        price: 47.4,
        image: '/images/course.png',
        category: 'Microsoft Azure',
        tags: ['Windows Server', 'Hybrid', 'Azure'],
        level: 'Advanced',
    },
    {
        id: 'az-801t00-a',
        code: 'AZ-801T00-A',
        title: 'Configuring Windows Server Hybrid Advanced Services [Cloud Slice Provided]',
        description: 'Configure advanced hybrid services',
        price: 47.4,
        image: '/images/course.png',
        category: 'Microsoft Azure',
        tags: ['Windows Server', 'Hybrid', 'Azure'],
        level: 'Advanced',
    },
];
