import mongoose from 'mongoose';

const OrderItemSchema = new mongoose.Schema({
    labId: { type: String, required: true },
    labCode: { type: String, required: true },
    labTitle: { type: String, required: true },
    quantity: { type: Number, required: true, min: 1 },
    priceUSD: { type: Number, required: true, min: 0 },
});

const OrderSchema = new mongoose.Schema({
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
    },
    orderNumber: {
        type: String,
        required: false, // Auto-generated by pre-save hook
        unique: true,
    },
    items: [OrderItemSchema],
    customerInfo: {
        fullName: { type: String, required: true },
        email: { type: String, required: true },
        company: String,
        phone: { type: String, required: true },
    },
    billingAddress: {
        street: { type: String, required: true },
        city: { type: String, required: true },
        state: { type: String, required: true },
        zipCode: { type: String, required: true },
        country: { type: String, required: true },
    },
    payment: {
        method: {
            type: String,
            enum: ['credit_card', 'purchase_order', 'razorpay'],
            required: true,
        },
        status: {
            type: String,
            enum: ['pending', 'completed', 'failed'],
            default: 'pending',
        },
        poNumber: String,
        stripePaymentIntentId: String,
        razorpayOrderId: String,
        razorpayPaymentId: String,
        razorpaySignature: String,
    },
    totals: {
        subtotal: { type: Number, required: true },
        tax: { type: Number, default: 0 },
        total: { type: Number, required: true },
        currency: { type: String, default: 'USD' },
    },
    status: {
        type: String,
        enum: ['pending', 'processing', 'completed', 'cancelled'],
        default: 'pending',
    },

    // Zoho Books integration
    zohoInvoiceId: {
        type: String,
        default: null
    },
    zohoInvoiceNumber: {
        type: String,
        default: null
    },
    zohoInvoiceUrl: {
        type: String,
        default: null
    }
}, {
    timestamps: true,
});

// Generate order number
// Generate order number
OrderSchema.pre('save', async function () {
    if (!this.orderNumber) {
        const date = new Date();
        const dateStr = date.toISOString().split('T')[0].replace(/-/g, '');
        // Use timestamp + random 4 chars to guarantee uniqueness
        const timestamp = Date.now().toString().slice(-6);
        const random = Math.floor(Math.random() * 1000).toString().padStart(3, '0');

        this.orderNumber = `ORD-${dateStr}-${timestamp}-${random}`;
    }
});

export default mongoose.models.Order || mongoose.model('Order', OrderSchema);
